//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHACHHANG
    {
        public KHACHHANG()
        {
            this.DONHANGs = new HashSet<DONHANG>();
        }
    
        public int MAKHACH { get; set; }
        public string TENKHACH { get; set; }
        public Nullable<System.DateTime> NGAYSINH { get; set; }
        public string GIOITINH { get; set; }
        public string DIENTHOAI { get; set; }
        public string TAIKHOAN { get; set; }
        public string EMAIL { get; set; }
        public string DIACHI { get; set; }
        public string MATKHAU { get; set; }
    
        public virtual ICollection<DONHANG> DONHANGs { get; set; }
    }
}
