//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        public SANPHAM()
        {
            this.CHITIETDONHANGs = new HashSet<CHITIETDONHANG>();
        }
    
        public string MASANPHAM { get; set; }
        public string TENSANPHAM { get; set; }
        public string HINHANH { get; set; }
        public string CHITIET { get; set; }
        public Nullable<int> SOLUONGTON { get; set; }
        public Nullable<int> GIABAN { get; set; }
        public Nullable<System.DateTime> NGAYCAPNHAT { get; set; }
        public string MALOAI { get; set; }
        public string MANSX { get; set; }
    
        public virtual LOAISP LOAISP { get; set; }
        public virtual NHASANXUAT NHASANXUAT { get; set; }
        public virtual ICollection<CHITIETDONHANG> CHITIETDONHANGs { get; set; }
    }
}
